version: "3.9"

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:pro
    volumes_from:
      - php
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - 4036:3306
    volumes:
      - ./mysql:/var/lib/mysql
    env:
      MYSQL_DATABASE: homestead
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }} 
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    image: php:8-fpm
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel

  nodejs:
    image: node:latest
    container_name: nodejs
    volumes:
      - ./src:/var/www/html
    ports:
      - "3000:3000"
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: composer
    command: ["composer", "install"]
    depends_on:
      - php
    volumes:
      - ./src/code:/app
    networks:
      - laravel
