name: Run Docker Compose

on:
  push:
    branches: [ master ]

jobs:
  docker:
    name: Docker Compose
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and run the app
        run: |
          docker-compose up -d

      - name: Run tests
        run: |
          docker-compose run composer install

      - name: Tear down the app
        run: |
          docker-compose down
          
      - run: npm ci
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ardinur/api-polban-news:latest
